# Álgebra Linear Exercícios

Agora que você ja estudou, e está por dentro dos principais conceitos que envolvem a **álgebra linear**, que tal fazer alguns exercícios para consolidar o conhecimento?

Para te ajudar preparamos exercícios das seguintes categorias:

- Escalares
- Vetores
- Matrizes

Para ter certeza de que você está no caminho certo, colocamos a resposta do exercício bem embaixo do enunciado de cada um. Para ver a resposta basta clicar em **RESPOSTA**!

Tente utilizando o Exemplo abaixo:

<details><summary><b>RESPOSTA</b></summary>
<p>

#### É isso ai!

```python
print("Você está pronto!")
```

</p>
</details>

Agora que você ja está pronto, vamos aos **Exercícios** !

---

## Escalares

**Exercicio 01)** Atribua o valor do escalar 20 a uma variável e imprima o valor na tela:

<details><summary><b>RESPOSTA</b></summary>
<p>

#### Copie e cole o código abaixo:

```python
escalar = 20
print(escalar)
```

</p>
</details>

In [1]:
escalar=20
print(escalar)

20


**Exercicio 02)** Um carro anda em uma via com uma velocidade média de 60 km/h! Atribua o valor do escalar a uma variável e imprima o valor na tela:

<details><summary><b>RESPOSTA</b></summary>
<p>

#### Copie e cole o código abaixo:

```python
velocidade = 60
print(velocidade)
```

</p>
</details>

In [3]:
velocidade_med=60
print(velocidade_med)

60


**Exercicio 03)** Para acompanhar o IMC de seu filho, todos os meses uma mãe atribui a altura e a massa dele a duas variáveis! 
- No mes de Janeiro a altura dele era de 1.30m e o peso 42kg! 
Como ela poderia fazer para atribuir os valores, utilizando python? Atribua os valores e imprima o resultado na tela!

<details><summary><b>RESPOSTA</b></summary>
<p>

#### Copie e cole o código abaixo:

```python
altura = 1.30
peso = 42
    
print(altura)
print(peso)
```

</p>
</details>

In [7]:
IMC={'mes':'Janeiro','altura':1.3,'peso':42}
print(IMC)

{'mes': 'Janeiro', 'altura': 1.3, 'peso': 42}


---
## Vetores

**Exercicio 04)** Crie um script para somar os vetores (1, 8, 5, 4), (5, 6, 4, 2) e imprima o resultado da soma na tela:

<details><summary><b>RESPOSTA</b></summary>
<p>

#### Copie e cole o código abaixo:

```python
import numpy as np
    
vetor1 = np.array([1, 8, 5, 4])
vetor2 = np.array([5, 6, 4, 2])

vetor3 = vetor1 + vetor2

print(vetor3)
```

</p>
</details>

In [10]:
import numpy as np

vetor1=np.array([1, 8, 5, 4])
vetor2=np.array([5, 6, 4, 2])

vetor3=vetor1+vetor2
vetor3

array([ 6, 14,  9,  6])

**Exercicio 05)** : Seguindo a imagem abaixo, imagine que você partindo da sua casa (origem), precisou ir até a farmácia e logo depois decidiu ir até o banco para pagar umas contas. Chegando em casa, você descobre esqueceu de pagar uma das contas e vai ter que voltar diretamente para o banco. Partindo da situação responda:

- Expresse o caminho de sua casa até a farmácia com um vetor;
- Expresse o caminho da farmácia até o banco com um vetor;
- Expresse o caminho da sua casa até o banco utilizando os vetores anteriormente criados;

*Obs - Cada um dos quarteirões da imagem valem 2km*


<img src="imagens/img07.png" width=300>

<details><summary><b>RESPOSTA</b></summary>
<p>

#### Copie e cole o código abaixo:

```python
import numpy as np

vetor_casa_farmacia = np.array((2, 4))
print(vetor_casa_farmacia)

vetor_farmacia_banco = np.array((2, 0))
print(vetor_farmacia_banco)

vetor_casa_banco = vetor_casa_farmacia + vetor_farmacia_banco
print(vetor_casa_banco) 
```

</p>
</details>

In [13]:
import numpy as np

casa=np.array([0,0])
farmacia=np.array([2,4])
banco=np.array([4,4])


casa_farmacia=farmacia-casa
farmacia_banco=banco-farmacia
casa_banco=casa+banco


print(casa_farmacia)
print(farmacia_banco)
print(casa_banco)

[2 4]
[2 0]
[4 4]


In [17]:
vetor=np.array([8,5,6])
escalar=4

print(escalar*vetor)

[32 20 24]


**Exercicio 07)** : Seguindo a imagem abaixo, imagine que certo dia, você descobriu que a farmácia se mudou para um novo endereço 3x mais longe de sua casa que o atual:

- Expresse o caminho de sua casa até a farmácia com um vetor;
- Expresse o novo vetor com caminho atual até a farmácia

*Obs - Cada um dos quarteirões da imagem valem 2km*


<img src="imagens/img07.png" width=300>

<details><summary><b>RESPOSTA</b></summary>
<p>

#### Copie e cole o código abaixo:

```python
import numpy as np

vetor_casa_farmacia = np.array((2, 4))
print(vetor_casa_farmacia)

nova_distancia = 3
print(nova_distancia)

vetor_casa_farmacia_atual = vetor_casa_farmacia * nova_distancia
print(vetor_casa_farmacia_atual) 

```

</p>
</details>

In [18]:
print(casa_farmacia*3)

[ 6 12]


---
## Matrizes

**Exercicio 08)** : Crie a matriz abaixo em python e imprima o resultado na tela:

<img src="imagens/img27.png" width=220>

<details><summary><b>RESPOSTA</b></summary>
<p>

#### Copie e cole o código abaixo:

```python
import numpy as np

matriz = np.array([[8, 7, 1], [6, 2, 6], [4, 0, 3]])
print(matriz)

```

</p>
</details>

In [22]:
import numpy as np
matriz=np.array([[8,7,1],[6,2,6],[4,0,3]]) # usar dois parenteses ?
matriz 

array([[8, 7, 1],
       [6, 2, 6],
       [4, 0, 3]])

**Exercicio 09)** : Cria um script para somar as matrizes abaixo e imprima o reultado na tela:

<img src="imagens/img26.png" width=200>
<img src="imagens/img27.png" width=220>

<details><summary><b>RESPOSTA</b></summary>
<p>

#### Copie e cole o código abaixo:

```python
import numpy as np

matriz1 = np.array([[2, 6, 8], [4, 5, 7], [5, 9, 3]])
print(matriz1)

matriz2 = np.array([[8, 7, 1], [6, 2, 6], [4, 0, 3]])
print(matriz2)

matriz3 = matriz1 + matriz2
print(matriz3)
```

</p>
</details>

In [1]:
import numpy as np

matriz1 = np.array([[2, 6, 8], [4, 5, 7], [5, 9, 3]])
print(matriz1)

matriz2 = np.array([[8, 7, 1], [6, 2, 6], [4, 0, 3]])
print(matriz2)

matriz3 = matriz1 + matriz2
print(matriz3)

[[2 6 8]
 [4 5 7]
 [5 9 3]]
[[8 7 1]
 [6 2 6]
 [4 0 3]]
[[10 13  9]
 [10  7 13]
 [ 9  9  6]]


In [23]:
import numpy as np

matriz1=np.array([[2,6,8],[4,5,7],[5,9,3]])
matriz2=np.array([[8,7,1],[6,2,6],[4,0,3]]) # usar dois parenteses ?

matriz_soma=matriz1+matriz2

print(matriz_soma)


[[10 13  9]
 [10  7 13]
 [ 9  9  6]]


**Exercicio 10)** : Imagine que você é o dono de uma grande franquia de doces e possui três lojas, cada uma das lojas vende Pitulitos, Balas e Picolés, possuindo em estoque as seguintes quantidades:

LOJA | PIRULITOS | BALAS | PICOLÉS
-----|-----------|-------|--------
Loja A | 500 | 300 | 200
Loja B | 400 | 500 | 100
Loja C | 300 | 200 | 600

Sabendo que cada um dos produtos tem o seguinte valor:

PRODUTO | PREÇO UNITÁRIO
--------|---------------
PIRULITO|0.50
BALA|0.20
PICOLÉ|1.50

Crie um script que calcula o lucro esperado para cada uma das lojas e indique qual é a loja mais lucrativa


<details><summary><b>RESPOSTA</b></summary>
<p>

#### Copie e cole o código abaixo:

```python
import numpy as np

matriz_lojas = np.array([[500, 300, 200], [400, 500, 100], [300, 200, 600]])
print(matriz_lojas)

matriz_precos = np.array([[0.5], [0.2], [1.5]])
print(matriz_precos)

matriz_lucro = matriz_lojas.dot(matriz_precos)
print(matriz_lucro)
```

</p>
</details>

In [5]:
import numpy as np

lojas=np.array([[500,300,200],[400,500,100],[300,200,600]])
print(lojas)

preço=np.array([0.5,0.2,1.5])
print(preço)

lucro = lojas.dot(preço)
print(lucro)

[[500 300 200]
 [400 500 100]
 [300 200 600]]
[0.5 0.2 1.5]
[ 610.  450. 1090.]
