# Álgebra Linear - Principais Conceitos

Ter uma base sólida de álgebra linear te ajudará muito lá na frente quando estiver lidando com assuntos de Data Science mais complexos mas que são construídos em cima destes conceitos. 

# Escalares ou Grandeza Escalar

É um único valor numérico associado a alguma unidade de medida para caracterizar uma grandeza da natureza

**Exemplos de Grandezas Escalares:**
- Massa
- Tempo
- Temperatura
- Comprimento

_Obs - Um escalar não precisa ter necessáriamente uma unidade de medida especificada_

## Definindo Escalares em Python

Para definir um escalar em Python, basta atribuir o seu valor único a uma variável.
**Exemplos**:
- Atribua o valor 36.5°C da temperatura corporal de uma pessoa a variável **temperatura** e imprima o resultado na tela

In [1]:
#Para atribuir o valor a uma variável, utilize o seguinte código: temperatura = 36.5
temperatura = 36.5
print(temperatura)

36.5


- Atribua o valor 20m da altura de uma casa a variável **altura** e imprima o resultado na tela

In [2]:
#Para atribuir o valor a uma variável, utilize o seguinte código: altura = 20
altura = 20
print(altura)

20


---

# Vetores

Por definição os vetores nada mais são que segmentos de Reta com:
- **Direção** - Direção da Reta (Horizontal, Vertical)
- **Sentido** - Sentido indicado pela orientação da reta
- **Modulo** - Intensidade ou Tamanho do Vetor

## Soma de Vetores

Para realizar a soma entre dois vetores, basta somar os itens de cada uma das posições do vetor em questão com os itens do vetor que se deseja efetuar a soma. Veja a imagem abaixo:

<img src="imagens/img14.png" width=200>

Muito simples né? Então vamos atribuir esses vetores a duas variáveis e somar para ver o resultado!

In [3]:
#Atribuindo os vetores a variaveis
vetor1 = (1, 2)
vetor2 = (1, 0)

In [4]:
#Somando as Variáveis
vetor3 = vetor1 + vetor2
print(vetor3)

(1, 2, 1, 0)


Como você pode notar, não funcionou muito bem né... 

Quando atribuimos os valores do vetor diretamente a uma variável e fazemos a soma com outra variavel contendo um vetor,  o que o Python faz é concatenar os dois vetores, formando um novo vetor concatenado.

Para resolver isso, precisaremos utilizar a biblioteca **Numpy**! 

O **Numpy** é uma poderosa biblioteca utilizada para fazer cálculos numéricos.

Para criar um vetor de fato, vamos utilizar o método **array** da biblioteca **Numpy**

In [5]:
#importando biblioteca Numpy (com o apelido carinhoso np)
import numpy as np

In [6]:
#atribuindo os vetores as variaveis
vetor1 = np.array((1, 2))
vetor2 = np.array((1, 0))

#somando os vetores e atribuindo o resultado em uma nova variavel
vetor3 = vetor1 + vetor2

In [7]:
#imprimindo resultado utilizando o print
print(vetor3)

[2 2]


In [8]:
#imprimindo o resultado sem o print
vetor3

array([2, 2])

Agora que ja entendemos como realizar a soma de matrizes, vejamos alguns exemplos:

 - Crie um script para somar o vetor (8, 6, 4, 6, 4) com o vetor (1, 2, 4, 5, 4) e imprima na tela o resultado

In [11]:
import numpy as np

vetor1=np.array((8,6,4,6,4))
vetor2=np.array((1,2,4,5,4))

vetor3 = vetor1+vetor2
vetor3

array([ 9,  8,  8, 11,  8])

In [13]:
#atribuindo os vetores as variaveis
vetor1 = np.array([8, 6, 4, 6, 4])
vetor2 = np.array([1, 2, 4, 5, 4])

#somando os vetores e atribuindo o resultado em uma nova variavel
vetor3 = vetor1 + vetor2

#imprimindo o resultado
print(vetor3)

[ 9  8  8 11  8]


 - Crie um script para somar o vetor (10, 15, 18, 22) com o vetor (4, 8, 3) e imprima na tela o resultado

In [15]:
vetor1=np.array((10, 15, 18, 22))
vetor2=np.array((4, 8, 3,0,0))
vetor3=vetor1+vetor2
vetor3

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [ ]:
#atribuindo os vetores as variaveis
vetor1 = np.array([10, 15, 18, 22])
vetor2 = np.array([4, 8, 3])

#somando os vetores e atribuindo o resultado em uma nova variavel
vetor3 = vetor1 + vetor2

#imprimindo o resultado
print(vetor3)

**Importante:** Como você pode notar no erro acima! A soma de vetores só é possível, quando os dois vetores foram da mesma dimensão (mesmo tamanho)

## Multiplicação de vetor por um escalar

Quando você multiplica um vetor por um número, esse número é chamado de escalar. Para realizar a operação, basta multiplicar cada item do vetor pelo escalar. Veja a imagem abaixo:

<img src="imagens/img16.png" width=160>

Vamos reproduzir o experimento em Python

In [16]:
#Atribuindo valor escalar 2 a variavel "escalar"
escalar = 2

#atribuindo os valores do vetor a variavel
vetor = np.array([1, 2])

In [17]:
#Multiplicando o Vetor
vetor_resultante = escalar * vetor

In [18]:
#imprimindo resultado
print(vetor_resultante)

[2 4]


Bem tranquilo né? Vamos fazer alguns exemplos:
- Crie um script que multiplique o vetor (2, 5, 6, 7) pelo escalar 8 e imprima o resultado na tela:

In [21]:
escalar=8
vetor=np.array((2,5,6,7))
print(vetor*8)

[16 40 48 56]


In [22]:
#Atribuindo valor escalar 2 a variavel "escalar"
escalar = 8

#atribuindo os valores do vetor a variavel
vetor = np.array([2, 5, 6, 7])

#Multiplicando o Vetor
vetor_resultante = escalar * vetor

#imprimindo resultado
print(vetor_resultante)

[16 40 48 56]


- Desenvolva um script que multiplique vetor (4, 6, 8) pelo escalar 4 e imprima o resultado na tela:

In [ ]:
#Atribuindo valor escalar 2 a variavel "escalar"
escalar = 4

#atribuindo os valores do vetor a variavel
vetor = np.array([4, 6, 8])

#Multiplicando o Vetor
vetor_resultante = escalar * vetor

#imprimindo resultado
print(vetor_resultante)

---

# Matrizes

Como cientista de dados você não irá analisar os seus temas de estudo somente ponto a ponto, ou vetor a vetor, por isso é necessário um sistema em que se possa sistematizar uma porção de observações. Utilizando o exemplo do material, poderíamos ter um conjunto de vetores, sendo cada vetor uma posição de nosso interesse, como a farmácia e o banco.

<img src="imagens/img07.png" width=200>


A partir dos vetores, podemos criar uma tabela indicando a distância da **Origem** até qualquer ponto do mapa, abaixo um exemplo com a Farmácia e o Banco


Movimentação | Farmácia | Banco
-------------|----------|------
X | 1 | 2
Y | 2 | 2


Se olharmos somente para os valores dessa tabela, temos uma **matriz** composta por:

<img src="imagens/img17.png" width=100>

Você pode  criar Matrizes com quantas linhas e com quantas colunas precisar

<img src="imagens/img18.png" width=350>

## Matrizes no Python

Para criar uma matriz no Python, também é necessário utilizar o método **array** da biblioteca **Numpy**.

Cada linha da matriz precisa estar entre **colchetes** "[ ]" e para representar as colunas, basta separar por vírgula:

- Exemplo: Linha em uma matriz: [1, 2, 3]

Cada nova linha da matriz, deve ser separa por virgula dentro de um novo par de colchetes, para representar a matriz <img src="imagens/img17.png" width=80> teremos:

- Exemplo: np.array([[1, 2], [2, 2]])

In [1]:
import numpy as np
np.array([[1, 2], [2, 2]])

array([[1, 2],
       [2, 2]])

# Operação de Matrizes

## Soma de Matrizes

Basta somar os elementos de mesma posição, veja abaixo:

<img src="imagens/img19.png" width=350>

Resultando em:

<img src="imagens/img20.png" width=80>

Vamos reproduzir o exemplo acima com Python:

In [2]:
#Atribuindo a primeira matriz
matriz1 = np.array([[1, 2],[0, 1], [3, 4]])
matriz1

array([[1, 2],
       [0, 1],
       [3, 4]])

In [3]:
#Atribuindo a primeira matriz
matriz2 = np.array([[0, 3],[2, 2], [1, 4]])
matriz2

array([[0, 3],
       [2, 2],
       [1, 4]])

In [4]:
#Somando as Matrizes
matriz3 = matriz1 + matriz2
print(matriz3)

[[1 5]
 [2 3]
 [4 8]]


## Multiplicação de matriz por um escalar

Cada elemento da matriz será multiplicado pelo escalar, veja abaixo:

<img src="imagens/img21.png" width=300>

Resultando em:

<img src="imagens/img22.png" width=90>


Vamos reproduzir o exemplo acima com Python:

In [5]:
#Atribuindo escalar em variável
escalar = 3
escalar

3

In [6]:
#Atribuindo a primeira matriz
matriz1 = np.array([[1, 2],[0, 1], [3, 4]])
matriz1

array([[1, 2],
       [0, 1],
       [3, 4]])

In [7]:
#Multiplicando a Matriz pelo Escalar
matriz2 = matriz1 * escalar
print(matriz2)

[[ 3  6]
 [ 0  3]
 [ 9 12]]


## Multiplicação de matrizes

Três coisas importantes para saber antes de prosseguir:

- Para podermos multiplicar duas matrizes o número de colunas da primeira matriz precisa ter o mesmo número de linhas da segunda matriz.
- A matriz resultante terá o número de linhas da primeira e o número de colunas da segunda.  
- A multiplicação de matrizes não é comutativa. Ou seja, A x B é diferente de B x A.


Vamos efetuar a seguinte multiplicação:

<img src="imagens/img23.png" width=300>

Nós vamos somar os produtos da linha da primeira matriz com a coluna da segunda. Olha só:

<img src="imagens/img24.png" width=550>

E ficamos com:

<img src="imagens/img25.png" width=120>


Vamos reproduzir o exemplo acima com Python:

In [8]:
#Atribuindo a primeira matriz
matriz1 = np.array([[1, 0, 3], [2, 1, 4]])
matriz1

array([[1, 0, 3],
       [2, 1, 4]])

In [9]:
#Atribuindo a segunda matriz
matriz2 = np.array([[0, 5], [3, 1], [4, 2]])
matriz2

array([[0, 5],
       [3, 1],
       [4, 2]])

In [13]:
matriz3 = matriz1.dot(matriz2)
print(matriz3)

[[12 11]
 [19 19]]


Para multiplicar as matrizes em Python, será necessário utilizar o médoto **.dot()** de uma matriz por outra

In [11]:
#Multiplicando as Matrizes
matriz3 = matriz1.dot(matriz2)
print(matriz3)

[[12 11]
 [19 19]]


## Materiais para aprofundamento

Com o que aprendeu por aqui será mais confortável mergulhar no material abaixo caso queira se aprofundar um pouco mais na Álgebra Linear.

[Curso de Álgebra linear da Khan Academy](https://pt.khanacademy.org/math/linear-algebra)

[Curso do MIT de Álgebra Linear](https://ocw.mit.edu/courses/mathematics/18-06-linear-algebra-spring-2010/video-lectures/)

[Série do canal 3Blue1Brown sobre Álgebra Linear](https://www.youtube.com/watch?v=fNk_zzaMoSs&list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab)
